apiVersion: v1
kind: Pod
metadata:
  name: disks
spec:
  containers:
  - name: disks
    image: ubuntu:14.04
    
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /tmp
  volumes:
    - name: mysql-persistent-storage
      gcePersistentDisk:
        # This disk must already exist.
        pdName: mysql-disk
        fsType: ext4