apiVersion: v1
kind: Pod
metadata:
  name: disks
spec:
  containers:
    - name: disks
      image: ubuntu:14.04
      volumeMounts:
        - name: php-fpm-pv
          mountPath: /php-fpm
  volumes:
    - name: php-fpm-pv
      persistentVolumeClaim:
        claimName: php-fpm-volume
        readOnly: true     