apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    name: mysql
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: meotimdihia/plf_mysql:1.0
          args:
            - --ignore-db-dir=lost+found
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3306
          volumeMounts:
            # This name must match the volumes.name below.
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: platform-admin
            - name: MYSQL_PASSWORD
              value: platform123
            - name: MYSQL_DATABASE
              value: platform
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            # This disk must already exist.
            pdName: mysql-disk
            fsType: ext4
