apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Delete 
  gcePersistentDisk:
    # This disk must already exist.
    pdName: disk-mysql
    fsType: ext4