apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: nginx
    tier: frontend
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: master
        image: nginx:1.7.10
        ports:
        - containerPort: 80