apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    name: nginx
spec:    
  replicas: 3
  selector: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.10
          ports:
          - containerPort: 80