apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete 
  gcePersistentDisk:
    # This disk must already exist.
    pdName: disk-php-fpm
    fsType: ext4