apiVersion: v1
kind: ReplicationController
metadata:
  name: php-fpm
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: php-fpm
    tier: backend
spec: 
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: master
        image:  meotimdihia/plf_php-fpm:1.0.3
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: platform-admin
        - name: MYSQL_PASSWORD
          value: platform123
        - name: MYSQL_DATABASE
          value: platform
        - name: REDIS_HOST
          value: redis