apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    name: redis
spec:    
  replicas: 3
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image:  redis:3-alpine