apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: redis
    tier: backend
spec:    
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: master
        image:  redis:3-alpine